game_series_num: 20

exception_game_ids:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 9
  - 19

exception_member:
  - before: 苏
    after: 蘇(機種依存文字)
  - before: 镜
    after: 鏡(機種依存文字)
  - before: 实况主本人
    after: Benren

column_num: 10

size_x: 150
size_y: 10

fig_top: 0.8
fig_bottom: 0.2

font: MS Mincho

font_size: 8

tasble_color:
  games:
    - bisque
    - lightblue
  shots:
    - bisque
    - lightblue